<?php

use Illuminate\Database\Seeder;
use App\Modelos\actividadcargo;

class ActividadcargosTableSeeder extends Seeder
{
    public function run()
    {
        //Actividaddes por Cargo de usuarios
        actividadcargo::create(['Cargo_id' => '1','Nombre' => 'Abogado']);
        actividadcargo::create(['Cargo_id' => '2','Nombre' => 'Cuentas Medicas']);
        actividadcargo::create(['Cargo_id' => '2','Nombre' => 'Contabilidad']);
        actividadcargo::create(['Cargo_id' => '2','Nombre' => 'Contratacion']);
        actividadcargo::create(['Cargo_id' => '2','Nombre' => 'Gestion Integral']);
        actividadcargo::create(['Cargo_id' => '2','Nombre' => 'Sistemas De Informacion']);
        actividadcargo::create(['Cargo_id' => '2','Nombre' => 'Gestion Integral Domiciliaria']);
        actividadcargo::create(['Cargo_id' => '2','Nombre' => 'Gestion Integral Juridica']);
        actividadcargo::create(['Cargo_id' => '2','Nombre' => 'Gestion Integral Municipios']);
        actividadcargo::create(['Cargo_id' => '2','Nombre' => 'Gestion Integral Odontologia']);
        actividadcargo::create(['Cargo_id' => '2','Nombre' => 'Incapacidades']);
        actividadcargo::create(['Cargo_id' => '2','Nombre' => 'Programador']);
        actividadcargo::create(['Cargo_id' => '2','Nombre' => 'Bienestar']);
        actividadcargo::create(['Cargo_id' => '3','Nombre' => 'Administrativo']);
        actividadcargo::create(['Cargo_id' => '3','Nombre' => 'Mantenimiento']);
        actividadcargo::create(['Cargo_id' => '3','Nombre' => 'Sistemas']);
        actividadcargo::create(['Cargo_id' => '3','Nombre' => 'Comunicaciones']);
        actividadcargo::create(['Cargo_id' => '4','Nombre' => 'Administrativo']);
        actividadcargo::create(['Cargo_id' => '4','Nombre' => 'Referencia Y Contrareferencia']);
        actividadcargo::create(['Cargo_id' => '4','Nombre' => 'Sistemas']);
        actividadcargo::create(['Cargo_id' => '4','Nombre' => 'Afiliaciones']);
        actividadcargo::create(['Cargo_id' => '4','Nombre' => 'Atencion Al Usuario Y Adminsiones']);
        actividadcargo::create(['Cargo_id' => '4','Nombre' => 'Contable']);
        actividadcargo::create(['Cargo_id' => '4','Nombre' => 'Coordinador De Sede Tipo D']);
        actividadcargo::create(['Cargo_id' => '4','Nombre' => 'Cuentas Medicas']);
        actividadcargo::create(['Cargo_id' => '4','Nombre' => 'Archivo']);
        actividadcargo::create(['Cargo_id' => '4','Nombre' => 'Calidad']);
        actividadcargo::create(['Cargo_id' => '4','Nombre' => 'Enfermeria']);
        actividadcargo::create(['Cargo_id' => '4','Nombre' => 'Enfermeria Domiciliaria']);
        actividadcargo::create(['Cargo_id' => '4','Nombre' => 'Farmacia']);
        actividadcargo::create(['Cargo_id' => '4','Nombre' => 'Farmacia']);
        actividadcargo::create(['Cargo_id' => '4','Nombre' => 'Farmacia Domiciliario']);
        actividadcargo::create(['Cargo_id' => '4','Nombre' => 'Mantenimiento']);
        actividadcargo::create(['Cargo_id' => '4','Nombre' => 'Tesoreria']);
        actividadcargo::create(['Cargo_id' => '4','Nombre' => 'Sistemas De Informacion']);
        actividadcargo::create(['Cargo_id' => '4','Nombre' => 'Digitacion De Farmacia']);
        actividadcargo::create(['Cargo_id' => '4','Nombre' => 'Enfermeria Administrativa']);
        actividadcargo::create(['Cargo_id' => '4','Nombre' => 'Compras']);
        actividadcargo::create(['Cargo_id' => '4','Nombre' => 'Gestion Humana']);
        actividadcargo::create(['Cargo_id' => '4','Nombre' => 'Radicacion']);
        actividadcargo::create(['Cargo_id' => '5','Nombre' => 'Afiliaciones']);
        actividadcargo::create(['Cargo_id' => '5','Nombre' => 'Compras E Infraestructura']);
        actividadcargo::create(['Cargo_id' => '5','Nombre' => 'Atención Domiciliaria']);
        actividadcargo::create(['Cargo_id' => '5','Nombre' => 'Auditoria De Cuentas']);
        actividadcargo::create(['Cargo_id' => '5','Nombre' => 'Farmacia']);
        actividadcargo::create(['Cargo_id' => '5','Nombre' => 'Gestion De Solicitudes']);
        actividadcargo::create(['Cargo_id' => '5','Nombre' => 'Referencia Y Contrareferencia']);
        actividadcargo::create(['Cargo_id' => '5','Nombre' => 'Departamental De Red']);
        actividadcargo::create(['Cargo_id' => '5','Nombre' => 'Medico']);
        actividadcargo::create(['Cargo_id' => '5','Nombre' => 'Atencion Al Usuario']);
        actividadcargo::create(['Cargo_id' => '5','Nombre' => 'Calidad']);
        actividadcargo::create(['Cargo_id' => '5','Nombre' => 'Gestion Social Y Comunitaria']);
        actividadcargo::create(['Cargo_id' => '5','Nombre' => 'Salud Y Seguridad En El Trabajo']);
        actividadcargo::create(['Cargo_id' => '5','Nombre' => 'Departamental De Red']);
        actividadcargo::create(['Cargo_id' => '5','Nombre' => 'Medica Municipios']);
        actividadcargo::create(['Cargo_id' => '5','Nombre' => 'Regional De Auditoria Y Calidad Medica']);
        actividadcargo::create(['Cargo_id' => '5','Nombre' => 'Contabilidad']);
        actividadcargo::create(['Cargo_id' => '5','Nombre' => 'Infraestructura Y Redes']);
        actividadcargo::create(['Cargo_id' => '5','Nombre' => 'Programa De Formacion']);
        actividadcargo::create(['Cargo_id' => '5','Nombre' => 'Informacion Y Tecnologia']);
        actividadcargo::create(['Cargo_id' => '5','Nombre' => 'Gestion Humana']);
        actividadcargo::create(['Cargo_id' => '5','Nombre' => 'Comunicaciones Y Publicidad']);
        actividadcargo::create(['Cargo_id' => '6','Nombre' => 'Domiciliaria']);
        actividadcargo::create(['Cargo_id' => '7','Nombre' => 'Contabilidad']);
        actividadcargo::create(['Cargo_id' => '8','Nombre' => 'Auditora']);
        actividadcargo::create(['Cargo_id' => '8','Nombre' => 'Coordinadora']);
        actividadcargo::create(['Cargo_id' => '8','Nombre' => 'Jefe']);
        actividadcargo::create(['Cargo_id' => '8','Nombre' => 'Jefe Domiciliaria']);
        actividadcargo::create(['Cargo_id' => '8','Nombre' => 'Auditora Cuentas Medicas']);
        actividadcargo::create(['Cargo_id' => '9','Nombre' => 'Domiciliaria']);
        actividadcargo::create(['Cargo_id' => '10','Nombre' => 'Domiciliaria']);
        actividadcargo::create(['Cargo_id' => '11','Nombre' => 'Salud Ocupacional']);
        actividadcargo::create(['Cargo_id' => '11','Nombre' => 'Auditor Cuentas Medicas']);
        actividadcargo::create(['Cargo_id' => '11','Nombre' => 'Atencion Domiciliaria']);
        actividadcargo::create(['Cargo_id' => '11','Nombre' => 'Auditor Concurrente']);
        actividadcargo::create(['Cargo_id' => '11','Nombre' => 'Auditor Calidad Medica']);
        actividadcargo::create(['Cargo_id' => '11','Nombre' => 'Auditor Gestion De Solicitudes Area Metropolitana']);
        actividadcargo::create(['Cargo_id' => '11','Nombre' => 'Auditor Gestion De Solicitudes Municipios']);
        actividadcargo::create(['Cargo_id' => '11','Nombre' => 'Auditor Gestion De Solicitudes']);
        actividadcargo::create(['Cargo_id' => '11','Nombre' => 'Lider Programa VIH']);
        actividadcargo::create(['Cargo_id' => '11','Nombre' => 'Medico General']);
        actividadcargo::create(['Cargo_id' => '11','Nombre' => 'Salud Ocupacional']);
        actividadcargo::create(['Cargo_id' => '11','Nombre' => 'Supernumerario']);
        actividadcargo::create(['Cargo_id' => '11','Nombre' => 'Experta En Reumatologia']);
        actividadcargo::create(['Cargo_id' => '11','Nombre' => 'Auditor']);
        actividadcargo::create(['Cargo_id' => '12','Nombre' => 'Mensajero']);
        actividadcargo::create(['Cargo_id' => '13','Nombre' => 'Nutricionista']);
        actividadcargo::create(['Cargo_id' => '14','Nombre' => 'Auditora']);
        actividadcargo::create(['Cargo_id' => '15','Nombre' => 'Oficios Generales']);
        actividadcargo::create(['Cargo_id' => '16','Nombre' => 'Orientador Usuarios']);
        actividadcargo::create(['Cargo_id' => '17','Nombre' => 'Sistemas De Informacion']);
        actividadcargo::create(['Cargo_id' => '18','Nombre' => 'Psicologo(a)']);
        actividadcargo::create(['Cargo_id' => '19','Nombre' => 'Farmacia']);
        actividadcargo::create(['Cargo_id' => '20','Nombre' => 'Sistemas De Informacion']);
        actividadcargo::create(['Cargo_id' => '21','Nombre' => 'Ocupacional Domiciliaria']);
        actividadcargo::create(['Cargo_id' => '21','Nombre' => 'Respiratorio']);
        actividadcargo::create(['Cargo_id' => '21','Nombre' => 'Ocupacional']);
        actividadcargo::create(['Cargo_id' => '21','Nombre' => 'Respiratorio Domiciliaria']);
        actividadcargo::create(['Cargo_id' => '22','Nombre' => 'Contabilidad']);
        actividadcargo::create(['Cargo_id' => '23','Nombre' => 'Contabilidad']);
        actividadcargo::create(['Cargo_id' => '24','Nombre' => 'Comercial Optometria']);
        actividadcargo::create(['Cargo_id' => '25','Nombre' => 'Calidad']);
        actividadcargo::create(['Cargo_id' => '26','Nombre' => 'Contabilidad']);
        actividadcargo::create(['Cargo_id' => '27','Nombre' => 'Agendas']);
        actividadcargo::create(['Cargo_id' => '27','Nombre' => 'Pyp']);
        actividadcargo::create(['Cargo_id' => '28','Nombre' => 'Subgerente']);
        actividadcargo::create(['Cargo_id' => '28','Nombre' => 'Financiero Y Administrativo']);
        actividadcargo::create(['Cargo_id' => '28','Nombre' => 'Talento Humano Y Control Interno']);
        actividadcargo::create(['Cargo_id' => '28','Nombre' => 'Medica']);
        actividadcargo::create(['Cargo_id' => '29','Nombre' => 'Gestion Humana']);
        actividadcargo::create(['Cargo_id' => '29','Nombre' => 'Gerencia']);
        actividadcargo::create(['Cargo_id' => '30','Nombre' => 'Gestion Humana']);
        actividadcargo::create(['Cargo_id' => '30','Nombre' => 'Medico']);
        actividadcargo::create(['Cargo_id' => '30','Nombre' => 'Calidad']);
        actividadcargo::create(['Cargo_id' => '30','Nombre' => 'Gestion Del Riesgo']);
        actividadcargo::create(['Cargo_id' => '31','Nombre' => 'Fiscal']);
        actividadcargo::create(['Cargo_id' => '32','Nombre' => 'Financiero']);
        actividadcargo::create(['Cargo_id' => '33','Nombre' => 'Gerente']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Alergologo']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Anestesiologo']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Cardiologo']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Cirugia Cardiovascular']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Cirugia General']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Cirugia General Y Cirugia Infantil']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Endocrino Pediatra']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Hematologa']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Infectologia']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Mastologo']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Medicina Bioenergetica']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Medicina Familiar']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Medicina Interna']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Medico Neuropsicologo']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Neumologia']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Neurocirugia']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Neurologia']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Oftalmologia']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Otorrinolaringologia']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Reumatologia']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Urologia']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Cirujano Plastico']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Cirujano Coloproctologo']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Pediatria']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Neurologo Pediatra']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Medicina Deportiva']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Internista']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Pediatra']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Neurociriujia']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Ortopedia']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Ginecologia']);
        actividadcargo::create(['Cargo_id' => '34','Nombre' => 'Endocrinologia']);
    
    }
}
