<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateRutaRcvsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('ruta_rcvs', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('programa_nefroporteccion')->nullable();
            $table->string('dx_hta')->nullable();
            $table->string('fecha_dx_hta')->nullable();
            $table->string('costo_hta')->nullable();
            $table->string('dx_dm')->nullable();
            $table->string('fecha_dx_dm')->nullable();
            $table->string('costo_dm')->nullable();
            $table->string('causa_erc')->nullable();
            $table->string('peso')->nullable();
            $table->string('talla')->nullable();
            $table->string('imc')->nullable();
            $table->string('clasificacion_imc')->nullable();
            $table->string('perimetro_abdominal')->nullable();
            $table->string('tension_arterial_sistolica')->nullable();
            $table->string('tension_arterial_diastolica')->nullable();
            $table->string('escala_framinghan')->nullable();
            $table->string('fecha_escala_framinghan')->nullable();
            $table->string('resultado_diabetes_escala_findrisk')->nullable();
            $table->string('fecha_escala_findrisk')->nullable();
            $table->string('resultado_rcv_control')->nullable();
            $table->string('fecha_tamizaje_rcv')->nullable();
            $table->string('resultado_riesgo_diabetes')->nullable();
            $table->string('fecha_tamizaje_riesgo_diabetes')->nullable();
            $table->string('escala_kaiser')->nullable();
            $table->string('dislipidemia')->nullable();
            $table->string('factores_riesgo')->nullable();
            $table->string('falla_organo_blaco')->nullable();
            $table->string('creatinina')->nullable();
            $table->string('fecha_creatinina')->nullable();
            $table->string('hba1c')->nullable();
            $table->string('fecha_hba1c')->nullable();
            $table->string('albuminuria')->nullable();
            $table->string('fecha_albuminuria')->nullable();
            $table->string('albuminuria_creatinuria')->nullable();
            $table->string('fecha_albuminuria_creatinuria')->nullable();
            $table->string('colesterol')->nullable();
            $table->string('fecha_colesterol')->nullable();
            $table->string('hdl')->nullable();
            $table->string('fecha_hdl')->nullable();
            $table->string('ldl')->nullable();
            $table->string('fecha_ldl')->nullable();
            $table->string('trigliceridos')->nullable();
            $table->string('fecha_trigliceridos')->nullable();
            $table->string('glicemias')->nullable();
            $table->string('fecha_glicemia')->nullable();
            $table->string('pth')->nullable();
            $table->string('fecha_pth')->nullable();
            $table->string('tfg')->nullable();
            $table->string('fecha_tfg')->nullable();
            $table->string('ekg')->nullable();
            $table->string('fecha_ekg')->nullable();
            $table->string('recibe_ieca')->nullable();
            $table->string('recibe_arados')->nullable();
            $table->string('recibe_hipoglicemiantes')->nullable();
            $table->string('actividad_fisica')->nullable();
            $table->string('fecha_prescripcion_actividad_fisica')->nullable();
            $table->string('atencion_recibida')->nullable();
            $table->string('fecha_educacion')->nullable();
            $table->string('tema')->nullable();
            $table->string('medicina_general_y_o_experto')->nullable();
            $table->string('medicina_interna_familiar')->nullable();
            $table->string('medicina_geriatrica')->nullable();
            $table->string('oftalmologia')->nullable();
            $table->string('nutricion')->nullable();
            $table->string('enfermeria')->nullable();
            $table->string('trabajo_social')->nullable();
            $table->string('dx_erc')->nullable();
            $table->string('estadio_erc')->nullable();
            $table->string('fecha_dx_erc_5')->nullable();
            $table->string('programa_seguimiento_erc_hta_dm')->nullable();
            $table->string('tfg_inicio_trr')->nullable();
            $table->string('modo_inicio_trr')->nullable();
            $table->string('fecha_inicio_trr')->nullable();
            $table->string('ingreso_unidad_renal')->nullable();
            $table->string('hemodialisis')->nullable();
            $table->string('dosis_dialisis_ktv')->nullable();
            $table->string('costo_hemodialisis')->nullable();
            $table->string('dialisis_peritoneal')->nullable();
            $table->string('dosis_dialisis_ktv_dpd')->nullable();
            $table->string('numero_horas_hemodialisis')->nullable();
            $table->string('peritonitis')->nullable();
            $table->string('costo_dp')->nullable();
            $table->string('vacuna_hepatitisb')->nullable();
            $table->string('fecha_dx_hepatitisb')->nullable();
            $table->string('fecha_dx_hepatitis_c')->nullable();
            $table->string('rerapia_no_dialitica_erc_5')->nullable();
            $table->string('costo_terapia_erc_5')->nullable();
            $table->string('hemoglobina')->nullable();
            $table->string('albumina_servica')->nullable();
            $table->string('fosforo')->nullable();
            $table->string('valoracio_nefrología')->nullable();
            $table->string('cancer_activo_12_meses')->nullable();
            $table->string('infeccion_cronica_activa_no_tratada')->nullable();
            $table->string('no_manifestado_deseo_trasplantarse')->nullable();
            $table->string('contraindicacion_esperanza_vida_menor_igual_6_meses')->nullable();
            $table->string('autocuidado_adherencia_tratamiento_posttrasplante')->nullable();
            $table->string('enfermedad_cardiaca_cerebrovascular_vascular')->nullable();
            $table->string('contraindicacion_infeccion_vih')->nullable();
            $table->string('contraindicacion_infeccion_vhc')->nullable();
            $table->string('contraindicacion_enfermedad_inmunologica_activa')->nullable();
            $table->string('contraindicacion_enfermedad_pulmonar_cronica')->nullable();
            $table->string('contraindicacion_otras_enfermedades_cronicas')->nullable();
            $table->string('fecha_realizacion_trasplante')->nullable();
            $table->string('ips_donde_espera')->nullable();
            $table->string('recibido_trasplante_renal')->nullable();
            $table->string('eps_realizo_trasplante')->nullable();
            $table->string('ips_realizo_trasplante')->nullable();
            $table->string('tipo_donante')->nullable();
            $table->string('costo_trasplante')->nullable();
            $table->string('presentado_complicacion_con_el_trasplante')->nullable();
            $table->string('fecha_dx_citomegalovirus')->nullable();
            $table->string('fecha_dx_infeccion_hongos')->nullable();
            $table->string('fecha_dx_presentado_infeccion_tuberculosis')->nullable();
            $table->string('fecha_dx_complicacion_cardiovascular')->nullable();
            $table->string('fecha_dx_complicacion_urologica')->nullable();
            $table->string('fecha_dx_complicacion_herida_quirurgica')->nullable();
            $table->string('fecha_primer_dx_cancer')->nullable();
            $table->string('medicamentos_inmunosupresores')->nullable();
            $table->string('recibio_metilprednisolona')->nullable();
            $table->string('recibio_azatriopina')->nullable();
            $table->string('recibio_ciclosporina')->nullable();
            $table->string('recibio_micofenalato')->nullable();
            $table->string('recibio_tracolimus')->nullable();
            $table->string('recibio_prednisona')->nullable();
            $table->string('recibio_mx_no_pos_1')->nullable();
            $table->string('recibio_mx_no_pos_2')->nullable();
            $table->string('recibio_mx_no_pos_3')->nullable();
            $table->string('episodios_rechazo')->nullable();
            $table->string('fecha_primer_episodios_rechazo_agudo')->nullable();
            $table->string('fecha_retorno_dialisis')->nullable();
            $table->string('numero_trasplantes_renales')->nullable();
            $table->string('costo_terapia_postrasplante')->nullable();
            $table->string('meses_prestacion_servicios')->nullable();
            $table->string('costo_total')->nullable();
            $table->string('eps_origen')->nullable();
            $table->string('novedad')->nullable();
            $table->string('causa_muerte')->nullable();
            $table->string('fecha_muerte')->nullable();
            $table->string('codigo_bdua')->nullable();
            $table->string('fecha_corte')->nullable();
            $table->string('fecha_inicio_tratamiento_enfermedad')->nullable();
            $table->string('Hospitalizacion')->nullable();
            $table->string('fecha_hospitalizacion')->nullable();
            $table->bigInteger('paciente_id')->nullable()->unsigned()->index();
            $table->foreign('paciente_id')->references('id')->on('pacientes');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('ruta_rcvs');
    }
}
