<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateCancerFiasTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('cancer_fias', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('Ocupacion')->nullable();
            $table->string('CodigoPertenenciaEtnica')->nullable();
            $table->string('GrupoPoblacional')->nullable();
            $table->string('NombreNeoplasia')->nullable();
            $table->string('FechaDx')->nullable();
            $table->string('FechaNotaRemisionMedico')->nullable();
            $table->string('FechaIngresoInstitucionRealizo')->nullable();
            $table->string('TipoEstudioRealizoDiagnostico')->nullable();
            $table->string('MotivoUsuarioNOTuvoDiagnostico')->nullable();
            $table->string('FechaRecoleccionMuestraEstudioHistopatologico')->nullable();
            $table->string('FechaInformHistopatologicoValido')->nullable();
            $table->string('CodigoValidoHabilitacionIPS')->nullable();
            $table->string('FechaPrimeraConsultaMedicoTratante')->nullable();
            $table->string('HistologiaTumorMuestraBiopsia')->nullable();
            $table->string('GradoDiferenciacionTumorAolidoMaligno')->nullable();
            $table->string('SiEsTumorSolido')->nullable();
            $table->string('FechaRealizoEstaEstadificacion')->nullable();
            $table->string('ParaCancerMama')->nullable();
            $table->string('ParaCancerMamaFechaRealizacion')->nullable();
            $table->string('ParaCancerMamaResultadoPrimera')->nullable();
            $table->string('ParaCancerColorrectalEstadificacionDukes')->nullable();
            $table->string('FechaEstadificacionDukes')->nullable();
            $table->string('EstadificacionLinfomaClinicaHodgkin')->nullable();
            $table->string('CancerProstataValorClasificacionGleason')->nullable();
            $table->string('ClasificacionRiesgoLeucemiasLinfomas')->nullable();
            $table->string('FechaClasificacionRiesgo')->nullable();
            $table->string('ObjetivoTratamientoMedicoInic')->nullable();
            $table->string('ObjetivoIntervencionMedicaPeriodoReporte')->nullable();
            $table->string('TieneAntecedenteOtroCancerPrimario')->nullable();
            $table->string('FechaDiagnosticoOtroCancerPrimario')->nullable();
            $table->string('TipoCancerAntecedente')->nullable();
            $table->string('RecibioUsuarioQuimioterapiaPeriodoCorteActual')->nullable();
            $table->string('FaseQuimioterapiaRecibioUsuarioCorte')->nullable();
            $table->string('UsuarioRecibioCorteQuimioterapiaPrefase')->nullable();
            $table->string('UsuarioRecibioCorteFaseQuimioterapiaInduccion')->nullable();
            $table->string('UsuarioRecibioCorteFaseQuimioterapIntensificacion')->nullable();
            $table->string('UsuarioRecibioCorteFaseQuimioterapiaConsolidacion')->nullable();
            $table->string('UsuarioRecibioCorteFaseQuimioterapiaReinduccion')->nullable();
            $table->string('UsuarioRecibiCorteFaseQuimioterapiaMantenimiento')->nullable();
            $table->string('UsuarioRecibioCorteFaseQuimioterapiaMantenimientoL')->nullable();
            $table->string('UsuarioRecibiCorteOtraFaseQuimioterapia')->nullable();
            $table->string('NumeroCiclosIniciadosPeriodoReporteActual')->nullable();
            $table->string('UbicacionTtemporalPrimerCicloRelacionOncologico')->nullable();
            $table->string('FechaInicioPrimerCicloQuimioterapiaCorte')->nullable();
            $table->string('NumeroIPSPrimerCicloCorte')->nullable();
            $table->string('CodigoIPS1PrimerCicloCorte')->nullable();
            $table->string('CodigoIPS2PrimerCicloCorte')->nullable();
            $table->string('MedicamentosAntineoplasicosPrimerCicloCorte')->nullable();
            $table->string('Medicamentoadm1PrimerEsquema')->nullable();
            $table->string('Medicamentoadm2PrimerEsquema')->nullable();
            $table->string('Medicamentoadm3PrimerEsquema')->nullable();
            $table->string('Medicamentoadm4PrimerEsquema')->nullable();
            $table->string('Medicamentoadm5PrimerEsquema')->nullable();
            $table->string('Medicamentoadm6PrimerEsquema')->nullable();
            $table->string('Medicamentoadm7PrimerEsquema')->nullable();
            $table->string('Medicamentoadm8PrimerEsquema')->nullable();
            $table->string('Medicamentoadm9PrimerEsquema')->nullable();
            $table->string('MedicamentoNoPOS1AdministradoUsuarioPrimerCiclo')->nullable();
            $table->string('MedicamentoNoPOS2AdministradoUsuarioPrimerCIclo')->nullable();
            $table->string('MedicamentoPOS3AdministradoUsuarioPrimerCiclo')->nullable();
            $table->string('RecibioQuimioterapiaIntratecalPrimerCiclo')->nullable();
            $table->string('FechaFinalizacionPrimerCicloCorte')->nullable();
            $table->string('CaracteristicasActualesPrimerCicloCorte')->nullable();
            $table->string('MotivoFinalizacionPrimerCiclo')->nullable();
            $table->string('UbicacionTemporalUltimoCicloCorteOncologico')->nullable();
            $table->string('FechaInicioUltimoCicloQuimioterapiaCorte')->nullable();
            $table->string('NumeroIPSSuministranUltimoCicloCorte')->nullable();
            $table->string('CodigoIPS1SuministraUltimoCicloReporte')->nullable();
            $table->string('CodigoIPS2SuministraUltimoCicloReporte')->nullable();
            $table->string('MedicamentosAntineoplasicosEspecialistaCancer')->nullable();
            $table->string('Medicamentoadm1UltimoEsquema')->nullable();
            $table->string('Medicamentoadm2UltimoEsquema')->nullable();
            $table->string('Medicamentoadm3UltimoEsquema')->nullable();
            $table->string('Medicamentoadm4UltimoEsquema')->nullable();
            $table->string('Medicamentoadm5UltimoEsquema')->nullable();
            $table->string('Medicamentoadm6UltimoEsquema')->nullable();
            $table->string('Medicamentoadm7UltimoEsquema')->nullable();
            $table->string('Medicamentoadm8UltimoEsquema')->nullable();
            $table->string('Medicamentoadm9UltimoEsquema')->nullable();
            $table->string('MedicamentoNoPOS1AdministradoUsuarioUltimoCiclo')->nullable();
            $table->string('MedicamentoNoPOS2AdministradoUsuarioUltimoCiclo')->nullable();
            $table->string('MedicamentoNoPOS3AdministradoUsuarioUltimoCiclo')->nullable();
            $table->string('RecibioQuimioterapiaIntratecalUltimoCicloCorte')->nullable();
            $table->string('FechaFinalizacionCicloUltimo')->nullable();
            $table->string('CaracteristicasActualesUltimoCicloCorte')->nullable();
            $table->string('MotivoFinalizacionPrematuraUltimoCiclo')->nullable();
            $table->string('SometidoUsuarioCirugiasCurativasPaliativas')->nullable();
            $table->string('NumeroCirugiasSometidoUsuarioPeriodoReporteActual')->nullable();
            $table->string('FechaRealizacionPrimeraCirugiaReporte')->nullable();
            $table->string('CodigoIPSRealizoPrimeraCirugiaCorte')->nullable();
            $table->string('CodigoPrimeraCirugia')->nullable();
            $table->string('UbicacionTemporalPrimeraCirugiaOncologico')->nullable();
            $table->string('FechaRealizacionUltimoProcedimientoQuirurgico')->nullable();
            $table->string('MotivoHaberRealizadoUltimaIntervencionQuirurgica')->nullable();
            $table->string('CodigoIPSRealizaUltimoProcedimientosQuirugicos')->nullable();
            $table->string('CodigoUltimaCirugia')->nullable();
            $table->string('UbicacionTemporalUltimaCirugiaOncologico')->nullable();
            $table->string('EstadoVitalFinalizarUnicaOltimaCirugia')->nullable();
            $table->string('RecibioUsuarioAlgunTipoRadioterapiaCorteActual')->nullable();
            $table->string('NumeroEsquemasRadioterapiaSuministradosCorteActual')->nullable();
            $table->string('FechaInicioPrimerUnicoEsquemaRadioterapia')->nullable();
            $table->string('UbicacionTemporalPrimerUnicoEsquemaRadioterapia')->nullable();
            $table->string('TipoRadioterapiaAplicadaPrimerUnicoEsquema')->nullable();
            $table->string('NumeroIPSSuministranPrimerUnicoEsquemaRadioterapia')->nullable();
            $table->string('CodigoIPS1SuministraRadioterapia')->nullable();
            $table->string('CodigoIPS2SuministraRadioterapia')->nullable();
            $table->string('FechaFinalizacionPrimerUnicoEsquemaRadioterapia')->nullable();
            $table->string('CaracteristicasActualesPrimerEsquemaRadioterapia')->nullable();
            $table->string('MotivoFinalizacionPrimerEsquemaRadioterapia')->nullable();
            $table->string('FechaInicioUltimoEsquemaRadioterapia')->nullable();
            $table->string('UbicacionTemporalUltimoEsquemaRadioterapia')->nullable();
            $table->string('TipoRadioterapiaAplicadaUltimoEsquemaRadioterapia')->nullable();
            $table->string('NumeroIPSSuministranUltimoEsquemaRadioterapia')->nullable();
            $table->string('CodigoIPS1SuministraRadioterapia1')->nullable();
            $table->string('CodigoIPS2SuministraRadioterapia1')->nullable();
            $table->string('FechaFinalizacionUltimoEsquemaRadioterapia')->nullable();
            $table->string('CaracteristicasActualesUltimoEsquemaRadioterapia')->nullable();
            $table->string('MotivoFinalizacionUltimoEsquemaRadioTerapia')->nullable();
            $table->string('RecibioUsuarioTtrasplanteCelulasProgenitoras')->nullable();
            $table->string('TipoTrasplanteRecibido')->nullable();
            $table->string('UbicacionTemporalTrasplanteOncologico')->nullable();
            $table->string('FechaTrasplante')->nullable();
            $table->string('CodigoIPSRealizoTrasplante')->nullable();
            $table->string('UsuarioRecibioCirugiaReconstructiva')->nullable();
            $table->string('FechaCirugia')->nullable();
            $table->string('CodigoIPSRealizoCirugiaReconstructiva')->nullable();
            $table->string('UsuarioValoradoConsultaProcedimientoPaliativo')->nullable();
            $table->string('UsuarioRecibioConsultaProcedimientoCuidadoPaliativ')->nullable();
            $table->string('UsuarioRecibioConsultaCuidadoPaliativo')->nullable();
            $table->string('UsuarioRecibioConsultaPaliativoEspecialista')->nullable();
            $table->string('UsuarioRecibioConsultaPaliativoGeneral')->nullable();
            $table->string('UsuarioRecibioConsultaPaliativoTrabajoSocial')->nullable();
            $table->string('UsuarioRecibioConsultaPaliativoNoEspecializado')->nullable();
            $table->string('FechaPrimeraConsultaPaliativoCorte')->nullable();
            $table->string('CodigoIPSRecibioPrimeraValoracionPaliativo')->nullable();
            $table->string('HaSidoValoradoUsuarioPorServicioPsiquiatria')->nullable();
            $table->string('FechaPrimeraConsultaServicioPsiquiatria')->nullable();
            $table->string('CodigoIPSRecibioPrimeraValoracionPsiquiatria')->nullable();
            $table->string('FueValoradoUsuarioPorProfesionalNutricion')->nullable();
            $table->string('FechaConsultaInicialNutricionCorte')->nullable();
            $table->string('CodigoIPSRecibioValoracionNutricion')->nullable();
            $table->string('UusuarioRecibioSoporteNutricional')->nullable();
            $table->string('UsuarioRecibidoTerapiasComplementariasRehabilitaci')->nullable();
            $table->string('TipoTratamientoRecibiendoUsuarioFechaCorte')->nullable();
            $table->string('ResultadoFinalManejoOncologicoCorte')->nullable();
            $table->string('EstadoVitalFinalizarCorte')->nullable();
            $table->string('NovedadADMINISTRATIVAUsuarioReporteAnterior')->nullable();
            $table->string('NovedadClinicaUsuarioFechaCorte')->nullable();
            $table->string('FechaDesafiliaciIonEPS')->nullable();
            $table->string('FechaMuerte')->nullable();
            $table->string('CausaMuerte')->nullable();
            $table->string('SerialBDUA')->nullable();
            $table->string('V134FechaCorte')->nullable();
            $table->string('paciente_id');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('cancer_fias');
    }
}
